config/routes.rb
Rails.application.routes.draw do
  root to: 'homepages#index'

  resources :works
  resources :users
  # get '/users', to: 'users#index', as: 'users'

  get '/login', to: 'users#login_form', as: 'login'
  post '/login', to: 'users#login'
  post '/logout', to: 'users#logout', as: 'logout'
  # get '/users/current', to: 'users#current', as: 'current_user'
  # get '/users/:id', to: 'users#show', as: 'user'

  post '/upvote/:id', to: 'users#upvote', as: 'upvote'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  has_many :votes


  acts_as_voter
end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :user
    belongs_to :work
end

app/models/work.rb
class Work < ApplicationRecord
  validates :title, presence: true
  acts_as_votable

  has_many :users, through: :votes
  has_many :votes

  def self.works_category(category)
    return Work.where(category: category).where.not(cached_votes_total: 0).order(title: :asc)
  end

  def self.top_ten_categories(category)
    works = self.works_category(category)
    works = works.sort_by {|work| work.votes_for.size }.reverse!
  end

  def self.top_work
    top_work = Work.order(cached_votes_total: :desc).first
    top_work
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])

    unless @user
      head :not_found
      return
    end
  end

  def login_form
    @user = User.new
  end

  def login
    username = params[:user][:username]
    user = User.find_by(username: username)

    if user 
      session[:user_id] = user.id
      flash[:success] = "Welcome back, #{username}."
    else
      user = User.create(username: username)
      session[:user_id] = user.id
      flash[:success] = "Welcome new user, #{user.username}."
    end
    redirect_to root_path
  end

  def current
    unless @user
      flash.now[:error] = "You must be logged in to do that."
      redirect_to root_path
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

  def upvote
    user = User.find_by(id: session[:user_id])

    unless user
      flash[:status] = :error
      flash[:message] = "Must be logged in to vote!"
      redirect_to works_path
    else
      @work = Work.find_by(id: params[:id])
      if user.voted_for? @work
      flash[:error] = "Cannot upvote the same media twice."
      redirect_to works_path
      else
        if @work.upvote_by user
          flash[:success] = "Successfully voted for #{@work.title}"
          redirect_to work_path(@work.id)
        else
          flash[:error] = "There was an error with your vote."
          redirect_to work_path(@work.id)
        end
      end
    end

  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :find_work, except: [:index, :new, :create]
  
  def index
    @albums = Work.where(category: "album")
    @books = Work.where(category: "book")
    @movies = Work.where(category: "movie")
  end

  def show 
    if @work.nil?
      flash[:failure] = "Your search returned no results."
      redirect_to root_path
    end
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)

    is_successful = @work.save

    if is_successful
      flash[:success] = "#{@work.title} was successfully created."
      redirect_to work_path(@work.id)
    else
      flash.now[:failure] = "Unable to create #{@work.category}"
      @work.errors.messages.each do |field, messages|
        flash.now[field] = messages
      end
      render(:new, status: :bad_request)
    end
  end

  def edit
    unless @work
      head :not_found
    end
  end

  def update
    if @work.update(work_params)
      flash[:success] = "Successfully updated #{@work.title}"
      redirect_to work_path(@work.id)
    else
      flash.now[:error] = "Unable to complete your update request."
      render(:edit, status: :bad_request)
    end

  end

  def destroy
    if !@work
      flash[:failure] = "Unable to delete the specified media."
      redirect_to root_path
    else
      @work.destroy
      flash[:success] = "Success! #{@work.title} is now deleted."
      redirect_to works_path
    end

  end

  private

  def work_params
    return params.require(:work).permit(:category, :title, :creator, :pub_year, :description, :votes)
  end

  def find_work
    @work = Work.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/homepages/index.html.erb
<main class="main">
  <section class="spotlight">
    <% top_work = Work.top_work %>
    <h2 class="spotlight_header">
      <span class="spotlight_title"> Media Spotlight: </span> 
      <%= link_to top_work.title, work_path(top_work.id), class:"spotlight_link" %> by <%= top_work.creator %>
    </h2>
      <p class="spotlight_description"> <%= top_work.cached_votes_total %> votes. <%= top_work.description %> </p>
  </section>

  <hr class="spotlight-border">

  <section class="top_ten_works_container">
    <section class="top">
      <h2 class="top_ten_header">Top Albums</h2>
        <% albums = Work.top_ten_categories("album")%>
        <ul class="list-group top_ten_list">
        <% albums.each do |album|%>
          <li class="list-group-item">
            <h4>
              <%= link_to album.title, work_path(album.id)%>
              <small class="top_creator">by <%= album.creator%> </small>  
            </h4>
            <p> <%= album.cached_votes_total%> votes </p>
          </li> 
        <%end%>
    </section>

    <section class="top">
      <h2 class="top_ten_header">Top Books</h2>
        <% books = Work.top_ten_categories("book")%>
        <ul class="list-group top_ten_list">
        <% books.each do |book|%>
          <li class="list-group-item">
            <h4>
              <%= link_to book.title, work_path(book.id)%>
              <small class="top_creator"> by <%= book.creator%> </small>  
            </h4>
            <p> <%= book.cached_votes_total%> votes </p>
          </li> 
        <%end%>
    </section>

    <section class="top">
      <h2 class="top_ten_header">Top Movies</h2>
        <% movies = Work.top_ten_categories("movie")%>
        <ul class="list-group top_ten_list">
        <% movies.each do |movie|%>
          <li class="list-group-item">
            <h4>
              <%= link_to movie.title, work_path(movie.id)%>
              <small class="top_creator"> by <%= movie.creator%> </small>  
            </h4>
            <p> <%= movie.cached_votes_total%> votes </p>
          </li> 
        <%end%>
    </section>
  </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MediaRanker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Gudea:400,700" rel="stylesheet">
  </head>
   
  <body>
    <header class="media_main_head">
      <h1 class="main-title"> 
        <a class="logo"> Media Ranker</a>
        <small class="tagline"> Ranking the Best of Everything</small>
      </h1>
      
      <nav class="nav-menu">
        <ul class="nav-container">
          <li class="nav-item"><%= link_to "View top media", root_path %></li>
          <li class="nav-item"><%= link_to "View all media", works_path %></li>
          <li class="nav-item"><%= link_to "Add a new work", new_work_path %></li>
          <li class="nav-item"><%= link_to "View all users", users_path %></li>
        </ul>

        <ul class="nav-container">
            <% if session[:user_id] %>
              <div class="user-link">
                <%= link_to "Logged in as #{User.find(session[:user_id]).username}", user_path(User.find_by(id: session[:user_id])), class: "btn btn-primary" %>
              </div>
                <%= button_to "Log out", logout_path(session[:user_id]), class: "btn btn-primary", method: :post %>
            <% else %>
                <%= link_to "Log in", login_path, class: "btn btn-primary"  %>
            <% end %>
        </ul>
      </nav>
    </header>er

    <section class="alert-container">
    <% if flash.count > 0 %>
        <section class="flash">
          <div class="alert">
            <% flash.each do |name, message| %>
              <% if message.class == Array %>
                <ul>
                <% message.each do |msg| %>
                  <li><%= name %>: <%= msg %> </li>
                <% end %>
              <% else %>
                <%= message %>
              <% end %>
                </ul>
            <% end %>
          </div>
        </section>
      <% end %>
    </section>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<main>
  <h2>List of Users</h2>

 <table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Votes</th>
      <th>Joined</th>
    </tr>
  </thead>
   <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to "#{user.username}", user_path(user.id) %></td>
        <td><%= user.votes.size %></td>
        <td><%= user.created_at.strftime('%b %d, %Y') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</main>

app/views/users/login_form.html.erb
<main>
  <h2>Log In</h2>

  <%= form_with model: @user, url: login_path do |f| %>
    <%= f.label :username %>
  <p> <%= f.text_field :username %> </p>

    <%= f.submit "Login", class: "btn btn-primary" %>
<% end %>
</main>

app/views/users/show.html.erb
<main>
  <header>
    <h3>User Summary: <%= @user.username %> </h3>
    <p>Joined Site <%= @user.created_at.strftime('%b %d, %Y') %> </p>
  </header> 

  <h4>Votes</h4>

  <table class="table">
    <thead>
      <tr>
        <th>Media Title</th>
        <th>Created By</th>
        <th>Published</th>
        <th>Category</th>
        <th>Voted On</th>
      </tr>
    </thead>
  
      <% if !@user.find_voted_items.empty? %>
        <% @user.find_voted_items.each do |work| %>
          <tr>
            <td>
              <%= work.title %>
            </td>

            <td>
              <%= work.creator %>
            </td>

            <td>
              <%= work.pub_year %>
            </td>

            <td>
              <%= work.category %>
            </td>
            
            <td>
              <%= work.created_at.strftime('%b %d, %Y') %>
            </td>
          </tr>
        <% end %>
      <%end%>
  </table>

  <%= link_to "See all users", users_path, class: "btn btn-secondary" %>
  <%= link_to "Back to media list", root_path, class: "btn btn-primary" %>

</main>

app/views/works/_form.html.erb
<main>
  <h2><%= form_title %></h2>
  <%= form_with model: @work do |f| %>
    <div>
      <p>
        <%= f.label :category %>
        <%= f.select :category, [ ["album"], ["book"], ["movie"] ]  %>
      </p>
      
      <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </p>

      <p>
        <%= f.label :creator %>
        <%= f.text_field :creator %>
      </p>

      <p>
        <%= f.label :pub_year %>
        <%= f.text_field :pub_year %>
      </p>

      <p>
        <%= f.label :description %>
        <%= f.text_field :description %>
      </p>

      <p>
        <%= f.submit action_name, class:"btn btn-primary" %>
      </p>
    </div>
  <% end %>
</main>

app/views/works/_media_table.html.erb
<main>
  <table class="table">
    <tr>
      <th>Votes</th>
      <th>Title</th>
      <th>Created by</th>
      <th>Published</th>
      <th>Upvote</th>
    </tr>

    <% works.order(cached_votes_total: :desc).each do |work| %>
    <tr>
      <td>
        <%= work.cached_votes_total %>
      </td>

      <td>
        <%= link_to "#{work.title}", work_path(work.id) %>
      </td>

      <td>
        <%= work.creator %>
      </td>

      <td>
        <%= work.pub_year %>
      </td>

      <td> 
        <%= link_to "Upvote", upvote_path(work.id), method: :post, class: "btn btn-primary" %> 
      </td>
    </tr>
    <% end %>

  </table>
</main>

app/views/works/edit.html.erb
<%= render partial: 'form',
locals: {
  form_title: 'Edit Work',
  action_type: 'Edit Work'
} %>

app/views/works/index.html.erb
<main>
  <h2>List of Works</h2>

  <h4>Albums</h4>

  <section>
    <%= render partial: 'media_table', locals: { :works => @albums } %>
  </section>

  <h4>Books</h4>

  <section>
    <%= render partial: 'media_table', locals: { :works => @books} %>
  </section>

  <h4>Movies</h4>

  <section>
    <%= render partial: 'media_table', locals: { :works => @movies} %>
  </section>
</main>

app/views/works/new.html.erb
<%= render partial: 'form',
locals: {
  form_title: 'Create New Work',
  action_type: 'Create Work'
} %>

app/views/works/show.html.erb
<main>
  <h2><%= @work.title %></h2>

  <p> Created by: <%= @work.creator %> </p>

  <p> Published: <%= @work.pub_year %> </p>

  <section>
    <%= link_to "Back to media ranks", works_path, class: "btn btn-primary" %>
    <%= link_to "Edit", edit_work_path(@work.id), class: "btn btn-primary" %>
    <%= link_to "Upvote", upvote_path(@work.id), method: :post, class: "btn btn-primary" %> 
    <%= link_to "Delete", work_path(@work.id), class: "btn btn-danger", method: :delete, data: { confirm: "You're deleting: #{@work.title}! Are you sure?" } %> 
  </section>

  <h2 class="work-votes-header">
    <td><%= @work.cached_votes_total %> votes for this <%= @work.category %></td>
  </h2>

  <table class="table">
      <thead>
        <tr>
          <th>User</th>
          <th>Date</th>
        </tr>
      </thead>
    
      <% @work.votes_for.includes(:voter).each do |vote| %>
        <tr>
          <td>
            <%= vote.voter.username %>
          </td>

          <td>
            <%= vote.updated_at.strftime('%b %d, %Y') %>
          </td>
        </tr>
      <% end %>
  </table>
</main>